spring:
  application:
    name: face-admin
  zipkin:
    base-url: http://misslxx.com:9411

server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://misslxx.com:8761/eureka/
