spring:
  application:
    name: face-eureka
  zipkin:
    base-url: http://localhost:9410
  boot:
    admin:
      client:
        url: http://localhost:8083

server:
  port: 8760

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://localhost:8761/eureka/
