spring:
  application:
    name: face-pay
  zipkin:
    base-url: http://112.74.41.246:9411
  boot:
    admin:
      client:
        url: http://112.74.41.246:8084
server:
  port: 8899
  
feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.32.1:8761/eureka/
