spring:
  application:
    name: face-rabbitmq
  zipkin:
    base-url: http://112.74.41.246:9411
  boot:
    admin:
      client:
        url: http://112.74.41.246:8084
  rabbitmq:
    host: misslxx.com
    port: 5672
    username: lxx
    password: Lcy100101
server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://112.74.41.246:8761/eureka/
