spring:
  application:
    name: face-rabbitmq
  mail:
    host: smtp.163.com
    username: zevjava@163.com
    password: li100101
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true
  zipkin:
    base-url: http://112.74.41.246:9411
  boot:
    admin:
      client:
        url: http://112.74.41.246:8084
  rabbitmq:
    host: misslxx.com
    port: 5672
    username: lxx
    password: Lcy100101
server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://112.74.41.246:8761/eureka/
msg:
  mail: zevjava@163.com
  subject: 登录成功邮件
  text:  您的账户{},在IP为<>的电脑登录成功!
      
