spring:
  application:
    name: face-redis
  boot:
    admin:
      client:
        url: http://misslxx.com:8084
  zipkin:
    base-url: http://misslxx.com:9411
  redis:
    host: 172.18.182.197
    port: 6379
    password: 
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

server:
  port: 8502

eureka:
  client:
    serviceUrl:
      defaultZone: http://misslxx.com:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
