spring:
  application:
    name: face-service-staff
  zipkin:
    base-url: http://112.74.41.246:9411
  boot:
    admin:
      client:
        url: http://112.74.41.246:8084
  datasource:
    druid:
      url: jdbc:mysql://112.74.41.246:3306/tsets?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: srt888
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8762
  
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070

eureka:
  client:
    serviceUrl:
      defaultZone: http://112.74.41.246:8761/eureka/
