spring:
  application:
    name: face-web-staff-feign
  zipkin:
    base-url: http://112.74.41.246:9411
  boot:
    admin:
      client:
        url: http://112.74.41.246:8084
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8765

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://112.74.41.246:8761/eureka/,http://localhost:8760/eureka/
