spring:
  application:
    name: face-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8083

server:
  port: 9410

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
      
management:
  metrics:
    web:
      server:
        auto-time-requests: false
