spring:
  application:
    name: face-zipkin
  boot:
    admin:
      client:
        url: http://112.74.41.246:8084

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://112.74.41.246:8761/eureka/
      
management:
  metrics:
    web:
      server:
        auto-time-requests: false
