spring:
  application:
    name: face-zuul
  zipkin:
    base-url: http://misslxx.com:9411
  boot:
    admin:
      client:
        url: http://misslxx.com:8084

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://misslxx.com:8761/eureka/,http://misslxx.com:8760/eureka/

zuul:
  routes:
    api-a:
      path: /api/staff/**
      serviceId: face-web-staff-feign
