spring:
  application:
    name: face-zuul
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/staff/**
      serviceId: face-web-staff-feign
